version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./runtime/logs:/var/log/nginx
      - ./:/var/www
    depends_on:
      - app

  app:
    build: docker/php
    working_dir: /var/www
    expose:
      - "9000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/var/www

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hart
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: